[tool.pyright]

exclude = ["tests", "**/__pycache__", "venv"]
pythonVersion = "3.9"
typeCheckingMode = "strict"

reportImportCycles = false
reportUnnecessaryIsInstance = false

reportCallInDefaultInitializer = "warning"
reportUnnecessaryTypeIgnoreComment = "warning"

reportPropertyTypeMismatch = "error"
