[tool.black]
line-length = 120

[tool.pyright]
exclude = ["**/tests/test_*.py", "**/__pycache__", ".venv/"]
pythonVersion = "3.9"
typeCheckingMode = "strict"

reportImportCycles = false
reportUnnecessaryIsInstance = false

reportCallInDefaultInitializer = "warning"
reportUnnecessaryTypeIgnoreComment = "warning"

reportPropertyTypeMismatch = "error"

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 125
