[tool.pyright]

pythonVersion = "3.9"
exclude = ["tests", "**/__pycache__", "venv"]
typeCheckingMode = "strict"

reportUnnecessaryIsInstance = false
reportImportCycles = false

reportCallInDefaultInitializer = "warning"
reportUnnecessaryTypeIgnoreComment = "warning"
reportPropertyTypeMismatch = "error"
